/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const MembershipPlan = IDL.Variant({
  'Premium' : IDL.Null,
  'Regular' : IDL.Null,
});
export const MembershipRequest = IDL.Record({
  'id' : IDL.Nat,
  'plan' : MembershipPlan,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllMembershipSubmissions' : IDL.Func(
      [],
      [IDL.Vec(MembershipRequest)],
      ['query'],
    ),
  'getMemberCount' : IDL.Func([], [IDL.Nat], []),
  'getMembershipSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementMemberCount' : IDL.Func([], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitMembership' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, MembershipPlan],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const MembershipPlan = IDL.Variant({
    'Premium' : IDL.Null,
    'Regular' : IDL.Null,
  });
  const MembershipRequest = IDL.Record({
    'id' : IDL.Nat,
    'plan' : MembershipPlan,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllMembershipSubmissions' : IDL.Func(
        [],
        [IDL.Vec(MembershipRequest)],
        ['query'],
      ),
    'getMemberCount' : IDL.Func([], [IDL.Nat], []),
    'getMembershipSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementMemberCount' : IDL.Func([], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitMembership' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, MembershipPlan],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };