/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
}
export type MembershipPlan = { 'Premium' : null } |
  { 'Regular' : null };
export interface MembershipRequest {
  'id' : bigint,
  'plan' : MembershipPlan,
  'fullName' : string,
  'email' : string,
  'phone' : string,
}
export interface _SERVICE {
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllMembershipSubmissions' : ActorMethod<[], Array<MembershipRequest>>,
  'getMemberCount' : ActorMethod<[], bigint>,
  'getMembershipSubmissionCount' : ActorMethod<[], bigint>,
  'incrementMemberCount' : ActorMethod<[], undefined>,
  'submitContactMessage' : ActorMethod<[string, string, string], bigint>,
  'submitMembership' : ActorMethod<
    [string, string, string, MembershipPlan],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];